_target_: src.models.opp_module.OppLitModule

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.001
  eps: 1e-8
  weight_decay: 0.025



scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  _partial_: true
  T_max: 1e5
  eta_min: 1e-5

net:
  _target_: src.models.components.opp_finetune.Tiny_Vit_11M
  pretrained: "/home/ds/Downloads/tiny_vit_11m_22kto1k_distill.pth"
