# @package _global_

defaults:
  - _self_
  - datamodule: opp.yaml # choose datamodule with `test_dataloader()` for evaluation
  - model: opp.yaml
  - logger: 'wandb'
  - trainer: default.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: logs/train/runs/2023-01-13_14-50-33/checkpoints/epoch_011.ckpt
